AWSTemplateFormatVersion: '2010-09-09'
Description: 'trip-project

  Rest API to manage trips

  '
Globals:
  Function:
    MemorySize: 512
    Timeout: 40
Outputs:
  CreateTripFunction:
    Description: CreateTrip Lambda Function ARN
    Value:
      Fn::GetAtt:
      - CreateTripFunction
      - Arn
  GetTripsByCountryFunction:
    Description: GetTripsByCountry Lambda Function ARN
    Value:
      Fn::GetAtt:
      - GetTripsByCountryFunction
      - Arn
Resources:
  CreateTripFunction:
    Properties:
      CodeUri: s3://aws-sam-fiap-deployt/896a140ec24d1c84f917b82d6bdddd3f
      Events:
        CreateTrip:
          Properties:
            Method: post
            Path: /trip
          Type: Api
      Handler: br.com.iwe.handler.CreateTrip::handleRequest
      Runtime: java8
    Type: AWS::Serverless::Function
  GetTripsByCountryFunction:
    Properties:
      CodeUri: s3://aws-sam-fiap-deployt/896a140ec24d1c84f917b82d6bdddd3f
      Events:
        GetTripsByCountry:
          Properties:
            Method: get
            Path: /trips/{country}
            RequestParameters:
              - method.request.querystring.city
              - method.request.querystring.starts
              - method.request.querystring.ends
          Type: Api
      Handler: br.com.iwe.handler.GetTripsByCountry::handleRequest
      Runtime: java8
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
